name: 'AppInspector'
description: 'Run ApplicationInspector Static Analysis'
inputs:
  location-to-scan:
    description: 'The path relative to repository root to scan.'
    required: false
    default: 'GITHUB_WORKSPACE'
  output-path:
    description: 'The path relative to file root to output to.'
    required: false
    default: 'AppInspectorResults'
  output-format:
    description: 'Output format [html|json|text]'
    required: false
    default: 'json'
  file-path-exclusions:
    description: 'Comma separated list of file path patterns to exclude.'
    required: false
    default: ','
  arguments:
    description: 'Other arguments to Application AppInspector'
    required: false
    default: ''

branding:
  icon: 'check-square'  
  color: 'green'  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.location-to-scan }}
    - ${{ inputs.output-path }}
    - ${{ inputs.output-format }}
    - ${{ inputs.file-path-exclusions }}
    - ${{ inputs.arguments }}
